apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard
# Using AWS EBS Storage
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2

reclaimPolicy: Retain
allowVolumeExpansion: true
mountOptions:
  - debug

volumeBindingMode: WaitForFirstConsumer